---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install R
      include: tasks/install-r.yml
    - name: Install R packages
      include: tasks/install-packages.yml
    - name: Install RStudio server
      include: tasks/install-rstudio-server.yml
