---
- name: Add APT repository
  apt_repository: repo="deb https://cran.rstudio.com/bin/linux/ubuntu/{{ ansible_distribution_release }}/" mode=644
  #apt_repository: repo="deb https://cran.r-project.org/bin/linux/ubuntu/bionic-cran35/" mode=664

- name: Add the APT key
  apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9

- name: Install R
  apt: name=r-base update_cache=yes
